version: '3.8'

volumes:
  postgres-data:
  grafana-data-config-datasources:
  grafana-data-config-dashboards:
  grafana-data-dashboards:

networks:
  back-tier:

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
        - ../.env
    volumes:
      - grafana-data-config-datasources:/workspaces/project-VinsiGit/.grafana/datasources
      - grafana-data-config-dashboards:/workspaces/project-VinsiGit/.grafana/dashboards
      - grafana-data-dashboards:/workspaces/project-VinsiGit/dashboards
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
        - ../.env
    ports:
      - "5432:5432"
    networks:
      - back-tier

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - back-tier

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - grafana-data-config-datasources:/etc/grafana/provisioning/datasources:ro
      - grafana-data-config-dashboards:/etc/grafana/provisioning/dashboards:ro
      - grafana-data-dashboards:/opt/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - back-tier
    user: "472"